export const FAVORITE_ACTION_TYPE = { // database
  ADD_FAV_LOADING: 'ADD_FAV_LOADING',
  ADD_FAV_SUCCESS: 'ADD_FAV_SUCCESS',
  ADD_FAV_FAIL: 'ADD_FAV_FAIL',
  DELETE_FAV_LOADING: 'DELETE_FAV_LOADING',
  DELETE_FAV_SUCCESS: 'DELETE_FAV_SUCCESS',
  DELETE_FAV_FAIL: 'DELETE_FAV_FAIL',
};

export const AUTH_ACTION_TYPE = { // database
  SIGN_UP_LOADING : 'SIGN_UP_LOADING',
  SIGN_UP_SUCCESS : 'SIGN_UP_SUCCESS',
  SIGN_UP_FAIL : 'SIGN_UP_FAIL',

  SIGN_IN_LOADING : 'SIGN_IN_LOADING',
  SIGN_IN_SUCCESS : 'SIGN_IN_SUCCESS',
  SIGN_IN_FAIL : 'SIGN_IN_FAIL',

  SIGN_OUT_LOADING : 'SIGN_OUT_LOADING',
  SIGN_OUT_SUCCESS : 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAIL : 'SIGN_OUT_FAIL',
};

export const BUSINESS_ACTION_TYPE = { // 3rd party api
  BUSINESS_200 : 'SUCCESS_GET_BUSINESS',
  BUSINESS_404 : 'FAIL_GET_BUSINESS',
  BUSINESS_LOADING : 'LOADING_GET_BUSINESS',
};

export const BUSINESS_LIST_ACTION_TYPE = {
  BUSINESS_LIST_200: 'SUCCESS_GET_BUSINESS_LIST',
  BUSINESS_LIST_404: 'FAIL_TO_GET_BUSINESS_LIST',
  BUSINESS_LIST_LOADING: 'LOADING_GET_BUSINESS_LIST'
};
